(()=>{'use strict';
const $=id=>document.getElementById(id);const state={vertices:[],faces:[],ground:[],filtered:false,originalText:'',bounds:null,rotX:-0.65,rotY:0.65,zoom:1,drag:null,format:'obj'};
const canvas=$('scene'),ctx=canvas.getContext('2d');
function status(s){$('status').textContent=s}
function fmt(n){return Number(n).toLocaleString('en-US',{maximumFractionDigits:1})}
function setProgress(p){$('progress').style.width=Math.max(0,Math.min(100,p))+'%'}
function parseOBJ(text){const verts=[],faces=[];for(const line of text.split(/\r?\n/)){const s=line.trim();if(!s||s[0]==='#')continue;const a=s.split(/\s+/);if(a[0]==='v'&&a.length>=4){const v=a.slice(1,4).map(Number);if(v.every(Number.isFinite))verts.push(v)}else if(a[0]==='f'&&a.length>=4){const ids=a.slice(1).map(t=>parseInt(t.split('/')[0],10)).map(i=>i<0?verts.length+i:i-1);for(let j=1;j<ids.length-1;j++){const f=[ids[0],ids[j],ids[j+1]];if(f.every(i=>i>=0&&i<verts.length))faces.push(f)}}}return {verts,faces}}
function parsePLY(text){const lines=text.split(/\r?\n/);let nv=0,nf=0,header=0,ascii=false;for(let i=0;i<lines.length;i++){const s=lines[i].trim();if(s==='format ascii 1.0')ascii=true;let m=s.match(/^element vertex (\d+)/);if(m)nv=+m[1];m=s.match(/^element face (\d+)/);if(m)nf=+m[1];if(s==='end_header'){header=i+1;break}}if(!ascii)throw Error('Only ASCII PLY files are supported by this version. Convert binary PLY to OBJ or ASCII PLY first.');const verts=[];for(let i=header;i<header+nv&&i<lines.length;i++){const n=lines[i].trim().split(/\s+/).map(Number);if(n.length<3||!n.slice(0,3).every(Number.isFinite))throw Error('Could not read PLY vertex coordinates.');verts.push(n.slice(0,3))}const faces=[];for(let i=header+nv;i<header+nv+nf&&i<lines.length;i++){const a=lines[i].trim().split(/\s+/).map(Number),count=a[0];if(!Number.isFinite(count)||count<3)continue;const ids=a.slice(1,count+1);for(let j=1;j<ids.length-1;j++){const f=[ids[0],ids[j],ids[j+1]];if(f.every(x=>Number.isInteger(x)&&x>=0&&x<verts.length))faces.push(f)}}return{verts,faces}}
function loadModel(model,name){if(!model.verts.length||!model.faces.length)throw Error('This file contains no readable triangle mesh.');state.vertices=model.verts;state.faces=model.faces;state.ground=[];state.filtered=false;state.originalText='';state.bounds=getBounds(state.vertices);$('empty').style.display='none';$('filterBtn').disabled=false;$('resetBtn').disabled=false;$('exportObj').disabled=true;$('exportPly').disabled=true;$('exportCsv').disabled=true;$('vertices').textContent=fmt(state.vertices.length);$('faces').textContent=fmt(state.faces.length);$('kept').textContent='—';$('ratio').textContent='—';$('viewSub').textContent=name;$('viewTag').textContent='ORIGINAL MESH';$('resultNote').textContent='Scan loaded. Run Extract ground to classify likely terrain triangles.';status('Scan loaded');setProgress(0);render()}
function getBounds(vs){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const v of vs)for(let k=0;k<3;k++){min[k]=Math.min(min[k],v[k]);max[k]=Math.max(max[k],v[k])}return{min,max,size:max.map((v,i)=>v-min[i]),center:max.map((v,i)=>(v+min[i])/2)}}
function normal(f){const a=state.vertices[f[0]],b=state.vertices[f[1]],c=state.vertices[f[2]],u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n);return l?n.map(x=>x/l):[0,0,0]}
function filterGround(){if(!state.faces.length)return;status('Filtering…');setProgress(5);const tol=+$('tolerance').value/100,slope=+$('slope').value*Math.PI/180,cell=+$('grid').value/100;const b=state.bounds,scale=Math.max(...b.size,0.001);const tolWorld=tol;const cellWorld=Math.max(cell,scale/250);const mins=new Map();const data=[];for(let i=0;i<state.faces.length;i++){const f=state.faces[i],pts=f.map(j=>state.vertices[j]);const cen=[0,1,2].map(k=>(pts[0][k]+pts[1][k]+pts[2][k])/3);const n=normal(f);const key=Math.floor((cen[0]-b.min[0])/cellWorld)+','+Math.floor((cen[2]-b.min[2])/cellWorld);const rec={f,cen,n,key};data.push(rec);const y=cen[1];if(!mins.has(key)||y<mins.get(key))mins.set(key,y);if(i%Math.max(1,Math.floor(state.faces.length/20))===0)setProgress(5+Math.floor(i/state.faces.length*30))}
// Estimate each cell's local low surface, then retain upward-facing faces within tolerance.
const kept=[];const minByKey=mins;for(let i=0;i<data.length;i++){const r=data[i],local=minByKey.get(r.key);let upward=r.n[1];if(upward<0){upward=-upward}const angle=Math.acos(Math.max(-1,Math.min(1,upward)));const isGround=(r.cen[1]-local)<=tolWorld && angle<=slope && upward>0.05;if(isGround)kept.push(r.f);if(i%Math.max(1,Math.floor(data.length/20))===0)setProgress(35+Math.floor(i/data.length*60))}
state.ground=kept;state.filtered=true;$('kept').textContent=fmt(kept.length);$('ratio').textContent=(kept.length/state.faces.length*100).toFixed(1)+'%';$('exportObj').disabled=!kept.length;$('exportPly').disabled=!kept.length;$('exportCsv').disabled=!kept.length;$('viewTag').textContent='GROUND CANDIDATES';$('resultNote').textContent=`Kept ${fmt(kept.length)} of ${fmt(state.faces.length)} triangles. This geometric filter can reject sloped/uneven ground or retain low vegetation; inspect the preview and adjust settings.`;setProgress(100);status('Ground extracted');render()}
function getFaces(){return state.filtered&&viewMode==='ground'?state.ground:state.faces}let viewMode='original';
function project(p,w,h){const c=state.bounds.center;let x=p[0]-c[0],y=p[1]-c[1],z=p[2]-c[2];const cy=Math.cos(state.rotY),sy=Math.sin(state.rotY),cx=Math.cos(state.rotX),sx=Math.sin(state.rotX);const x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y*cx-z1*sx;const z2=y*sx+z1*cx;const scale=Math.min(w,h)*0.68/Math.max(...state.bounds.size,0.01)*state.zoom;return{x:w/2+x1*scale,y:h/2-y1*scale,z:z2}}
function render(){if(!state.vertices.length){ctx.clearRect(0,0,canvas.width,canvas.height);return}const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1714';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#203a30';ctx.lineWidth=1;for(let i=0;i<10;i++){const x=w*i/9;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();const y=h*i/9;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
const faces=getFaces();if(!faces.length){ctx.fillStyle='#c0d5c8';ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillText('No ground triangles found — increase tolerance or slope limit.',w/2,h/2);return}const stride=Math.max(1,Math.ceil(faces.length/45000));const polys=[];for(let i=0;i<faces.length;i+=stride){const f=faces[i],p=f.map(id=>project(state.vertices[id],w,h));if(p.some(v=>!Number.isFinite(v.x)||!Number.isFinite(v.y)))continue;const n=normal(f);polys.push({p,z:(p[0].z+p[1].z+p[2].z)/3,shade:Math.abs(n[1])})}polys.sort((a,b)=>a.z-b.z);for(const poly of polys){ctx.beginPath();ctx.moveTo(poly.p[0].x,poly.p[0].y);ctx.lineTo(poly.p[1].x,poly.p[1].y);ctx.lineTo(poly.p[2].x,poly.p[2].y);ctx.closePath();if(viewMode==='ground'){const g=Math.round(115+poly.shade*90);ctx.fillStyle=`rgb(40,${g},${Math.round(85+poly.shade*65)})`;ctx.strokeStyle='rgba(160,255,185,.25)'}else{ctx.fillStyle=`rgb(${Math.round(35+poly.shade*40)},${Math.round(92+poly.shade*55)},${Math.round(77+poly.shade*45)})`;ctx.strokeStyle='rgba(155,222,190,.14)'}ctx.fill();if(faces.length<15000)ctx.stroke()}}
$('fileInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{status('Reading file…');const text=await file.text();const ext=file.name.split('.').pop().toLowerCase();const model=ext==='ply'?parsePLY(text):parseOBJ(text);loadModel(model,file.name)}catch(err){status('Import failed');alert('Could not import this scan: '+err.message)}e.target.value=''});
$('filterBtn').onclick=()=>{try{filterGround()}catch(e){status('Filter error');alert(e.message)}};$('resetBtn').onclick=()=>{state.filtered=false;viewMode='original';selectView('original');$('kept').textContent='—';$('ratio').textContent='—';$('exportObj').disabled=true;$('exportPly').disabled=true;$('exportCsv').disabled=true;$('viewTag').textContent='ORIGINAL MESH';$('resultNote').textContent='Showing original scan.';setProgress(0);status('Original scan');render()};
function selectView(mode){viewMode=mode;$('viewOriginal').classList.toggle('active',mode==='original');$('viewGround').classList.toggle('active',mode==='ground');$('viewTag').textContent=mode==='ground'?'GROUND CANDIDATES':'ORIGINAL MESH';render()}$('viewOriginal').onclick=()=>selectView('original');$('viewGround').onclick=()=>{if(!state.filtered){alert('Run Extract ground first.');return}selectView('ground')};
for(const [id,out,suffix] of [['tolerance','tolOut',' cm'],['slope','slopeOut','°'],['grid','gridOut',' cm']])$(id).addEventListener('input',()=>$(out).textContent=$(id).value+suffix);
function download(name,content,type='text/plain'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function objText(faces){const used=new Map(),verts=[];for(const f of faces)for(const id of f)if(!used.has(id)){used.set(id,verts.length+1);verts.push(state.vertices[id])}let out='# LiDAR Ground Mapper export\n';for(const v of verts)out+=`v ${v[0]} ${v[1]} ${v[2]}\n`;for(const f of faces)out+=`f ${f.map(id=>used.get(id)).join(' ')}\n`;return out}
function getExportFaces(){if(!state.ground.length)throw Error('No ground triangles to export. Run Extract ground first.');return state.ground}
$('exportObj').onclick=()=>{try{download('ground-only.obj',objText(getExportFaces()))}catch(e){alert(e.message)}};
$('exportPly').onclick=()=>{try{const faces=getExportFaces(),used=new Map(),verts=[];for(const f of faces)for(const id of f)if(!used.has(id)){used.set(id,verts.length);verts.push(state.vertices[id])}let out=`ply\nformat ascii 1.0\nelement vertex ${verts.length}\nproperty float x\nproperty float y\nproperty float z\nelement face ${faces.length}\nproperty list uchar int vertex_indices\nend_header\n`;for(const v of verts)out+=v.join(' ')+'\n';for(const f of faces)out+=`3 ${f.map(id=>used.get(id)).join(' ')}\n`;download('ground-only.ply',out)}catch(e){alert(e.message)}};
$('exportCsv').onclick=()=>{try{const faces=getExportFaces(),ids=new Set();faces.forEach(f=>f.forEach(id=>ids.add(id)));let out='x,y,z\n';for(const id of ids)out+=state.vertices[id].join(',')+'\n';download('ground-points.csv',out,'text/csv')}catch(e){alert(e.message)}};
$('demoBtn').onclick=()=>{const verts=[],faces=[],N=44;for(let z=0;z<N;z++)for(let x=0;x<N;x++){const xx=(x/(N-1)-.5)*12,zz=(z/(N-1)-.5)*12;const yy=.18*Math.sin(xx*.7)*Math.cos(zz*.55)+.06*Math.sin(zz*1.4);verts.push([xx,yy,zz])}for(let z=0;z<N-1;z++)for(let x=0;x<N-1;x++){const a=z*N+x,b=a+1,c=a+N,d=c+1;faces.push([a,c,b],[b,c,d])} // synthetic trees as vertical triangles
for(const [tx,tz,height] of [[-2,-1,2.5],[2,1,2.1],[3,-3,1.8],[-4,3,1.6]]){const base=verts.length;for(let j=0;j<5;j++){const a=j*Math.PI*2/5;verts.push([tx+Math.cos(a)*.12,0,tz+Math.sin(a)*.12]);verts.push([tx+Math.cos(a)*.12,height*.55,tz+Math.sin(a)*.12])}const top=verts.length;verts.push([tx,height,tz]);for(let j=0;j<5;j++){const a=base+j*2,b=base+((j+1)%5)*2,at=a+1,bt=b+1;faces.push([a,b,at],[b,bt,at],[at,bt,top])}}loadModel({verts,faces},'Sample terrain with synthetic vegetation')};
let last=null;canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;const dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;state.rotY+=dx*.009;state.rotX=Math.max(-1.5,Math.min(1.5,state.rotX+dy*.009));state.drag={x:e.clientX,y:e.clientY};render()});canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('pointercancel',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(5,state.zoom*(e.deltaY>0?.9:1.1)));render()},{passive:false});let pinchDist=0;canvas.addEventListener('touchstart',e=>{if(e.touches.length===2)pinchDist=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinchDist){state.zoom=Math.max(.25,Math.min(5,state.zoom*d/pinchDist));render()}pinchDist=d}},{passive:true});window.addEventListener('resize',render);
if('serviceWorker'in navigator&&location.protocol.startsWith('http')){};
})();
